# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_1)\
$os\
$username\
[](bg:color_2 fg:color_1)\
$directory\
[](fg:color_2 bg:color_3)\
$git_branch\
$git_status\
[](fg:color_3 bg:color_4)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:color_4 bg:color_5)\
$docker_context\
[](fg:color_5 bg:color_6)\
$time\
[ ](fg:color_6)\
"""

add_newline = true
command_timeout = 2000
palette = 'rose_pine'

[palettes.rose_pine]
color_0 = '#cba6f7'
color_1 = '#f5c2e7'
color_2 = '#f38ba8'
color_3 = '#fab387'
color_4 = '#a6e3a1'
color_5 = '#89dceb'
color_6 = '#b4befe'
color_fg = '#1e1e2e'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = false
style_user = "bg:#f5c2e7 fg:color_fg"
style_root = "bg:#f5c2e7 fg:color_fg"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:color_0"
disabled = true # Disabled by default

[directory]
style = "bg:color_2 fg:color_fg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = "c"
style = "bg:color_4 fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "docker"
style = "bg:color_5 g:color_fg"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = "elixir"
style = "bg:color_4 fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "elm"
style = "bg:color_4 fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:color_3 fg:color_fg"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color_3 fg:color_fg"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "go"
style = "bg:color_4 fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:color_4 fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "haskell"
style = "bg:color_4 fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "java"
style = "bg:color_4 fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "julia"
style = "bg:color_4 fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "node"
style = "bg:color_4 fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "nim"
style = "bg:color_4 fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "rust"
style = "bg:color_4 fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "scala"
style = "bg:color_4 fg:color_fg"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:color_6 fg:color_fg"
format = '[ ♥ $time ]($style)'
